spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/alina
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 28080

openAi:
  token: <your token>
  timeoutSeconds: 120