spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/alina
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  ai:
    openai:
      api-key: <add your key here>

server:
  port: 28080

# Storage configuration
# Options: mongodb (default), local
storage:
  type: local
  local:
    base:
      path: data

